trigger:
- main

variables:
  azureSubscriptionEndpoint: 'Azure for Students (3877b576-d00d-40b8-861a-13def96a6fd6)'
  azureContainerRegistry: 'cvimprover.azurecr.io'
  dockerComposePath: '**/docker-compose.yml' # Update this path to your docker-compose.yml file
  imageName: 'cvimprover:$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      displayName: 'Build and push Docker image using Docker Compose'
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        azureContainerRegistry: '{"loginServer":"$(azureContainerRegistry)", "id":"/subscriptions/3877b576-d00d-40b8-861a-13def96a6fd6/resourceGroups/cv-improver_group/providers/Microsoft.ContainerRegistry/registries/cvimprover"}'
        dockerComposeFile: $(dockerComposePath)
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up --build -d' # Builds, (re)creates, starts, and attaches to containers for a service.

